name: evaluation-tutorial

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pandas
  - seaborn
  - jupyter
  - pip
  - pip:
    - --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple
    - scikit-learn
